#ifndef COLOR_H
#define COLOR_H

typedef enum {
    RESET,
    BOLD,
    UNDERLINE,
    REVERSE
} TextAttribute;

typedef enum {
    BLACK,
    RED,
    GREEN,
    YELLOW,
    BLUE,
    MAGENTA,
    CYAN,
    WHITE,
    BLACK_BG,
    RED_BG,
    GREEN_BG,
    YELLOW_BG,
    BLUE_BG,
    MAGENTA_BG,
    CYAN_BG,
    WHITE_BG,
    BLACK_BOLD,
    RED_BOLD,
    GREEN_BOLD,
    YELLOW_BOLD,
    BLUE_BOLD,
    MAGENTA_BOLD,
    CYAN_BOLD,
    WHITE_BOLD,
    BLACK_UNDERLINE,
    RED_UNDERLINE,
    GREEN_UNDERLINE,
    YELLOW_UNDERLINE,
    BLUE_UNDERLINE,
    MAGENTA_UNDERLINE,
    CYAN_UNDERLINE,
    WHITE_UNDERLINE,
    BLACK_HI,
    RED_HI,
    GREEN_HI,
    YELLOW_HI,
    BLUE_HI,
    MAGENTA_HI,
    CYAN_HI,
    WHITE_HI,
    BLACK_HI_BG,
    RED_HI_BG,
    GREEN_HI_BG,
    YELLOW_HI_BG,
    BLUE_HI_BG,
    MAGENTA_HI_BG,
    CYAN_HI_BG,
    WHITE_HI_BG
} Color;

#endif // COLOR_H